# Site settings
title: Kaybeez
email: kaybeez112@gmail.com
description: 
  Musings and ramblings of SunKay... Anything goes.. Consume at your own peril...
  Standard disclaimers apply
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sunkay.github.io" # the base hostname & protocol for your site
twitter_username: sunkay
github_username:  sunkay

paginate:         1


# Build settings
markdown: kramdown

highlighter: pygments

# Permalinks
permalink:        pretty

# This is the list of pages to incldue in the header of the website.
pages_list:       {'About':'/about','Archive':'/archive','Feed':'/atom.xml'}
