# Site settings
title: Kaybeez
email: kaybeez112@gmail.com
description:
  Musings ... Didn't die, won't quit ...
  Standard disclaimers apply
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sunkay.github.io" # the base hostname & protocol for your site
twitter_username: sunkay
github_username:  sunkay
theme: jekyll-theme-modernist

paginate:         1


# Build settings
markdown: kramdown

highlighter: pygments

# Permalinks
permalink:        pretty

# This is the list of pages to incldue in the header of the website.
pages_list:       {'About':'/about','Archive':'/archive','sunkay':'https://github.com/sunkay','Feed':'/atom.xml'}
